apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflix-app
  labels:
    app: myflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myflix-app
  template:
    metadata:
      labels:
        app: myflix-app
    spec:
      containers:
      - name: myflix-app
        image: gokulananths/myflix:latest
        ports:
        - containerPort: 80